apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # these labels belongs to deplyment resource
  labels:
    project: expense
    component: frontend
    environment: dev
    tier: web
spec:
  # modify replicas according to your case
  replicas: {{ .Value.deployment.replicas }}
  selector:
    matchLabels:
      project: expense
      component: frontend
      environment: dev
      tier: web
    # below is the pod defination
  template:
    metadata:
      labels:
        project: expense
        component: frontend
        environment: dev
        tier: web
    spec:
      containers:
      - name: frontend
        image: charan466/frontend:{{ .Value.deployment.imageVersion }}
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        # env:
        #     - name: frontend_ROOT_PASSWORD
        #       value: Expenseweb@1
        # envFrom:
        # - configMapRef:
        #     name: frontend
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend
          items:
          - key: nginx.conf
            path: nginx.conf