apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    project: expense
    component: frontend
    environment: dev
    tier: web
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: {{ .Value.configmap.port1 }} #target-port